### ISSUE TITLE
Getting almost same values for 2p5 to 10p

### ISSUE THREAD

**Issue by firefly-serenity** [Sensirion/embedded-sps#40]
When measuring particles I receive almost the identical values for the sizes 2.5, 4 and 10.
Is this because there are no additional particles of those sizes, or is this a problem with the sensor?

The same issue has been discussed here, but there could not be found a good explanation: https://github.com/paulvha/sps30/issues/3

Have you had similar experiences and/or do you have an explanation for the behaviour?

Thanks in advance!

**Comment by abrauchli** [comment]
I'm posting the reply in the linked and close this thread to avoid forking. Generally please refer to Sensirion support for information not related to the driver.
